/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness and database connectivity.
         */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register
         * @description Create an account. The first account registered becomes the admin.
         */
        post: operations["register_api_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Exchange credentials for a short-lived access token and a refresh cookie.
         */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh
         * @description Rotate the refresh cookie and mint a new access token.
         */
        post: operations["refresh_api_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Revoke the current refresh session and clear its cookie.
         */
        post: operations["logout_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Me
         * @description The authenticated account.
         */
        get: operations["me_api_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/credentials": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Credentials
         * @description List stored credentials with masked values.
         */
        get: operations["list_credentials_api_credentials_get"];
        put?: never;
        /**
         * Store
         * @description Store an API key, encrypted at rest. Re-posting the same slot replaces it.
         */
        post: operations["store_api_credentials_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/credentials/{credential_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Credential
         * @description Permanently delete a stored credential.
         */
        delete: operations["delete_credential_api_credentials__credential_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/market/instruments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Instruments
         * @description Tracked instruments with their last quote and how stale it is.
         */
        get: operations["list_instruments_api_market_instruments_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/market/instruments/{symbol}/bars": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Instrument Bars
         * @description Stored daily bars, oldest first.
         */
        get: operations["instrument_bars_api_market_instruments__symbol__bars_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/market/quotes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Quotes
         * @description Live quotes, fetched through the provider chain for each symbol's asset class.
         */
        get: operations["quotes_api_market_quotes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/market/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Providers
         * @description Per-provider configuration and health. Credential values are masked, never returned.
         */
        get: operations["providers_api_market_providers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/market/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sync
         * @description Refresh the tracked universe for one asset class, optionally pulling bars too.
         */
        post: operations["sync_api_market_sync_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Portfolios
         * @description Every portfolio belonging to the current account.
         */
        get: operations["list_portfolios_api_portfolios_get"];
        put?: never;
        /**
         * Create Portfolio
         * @description Open a paper portfolio. The initial capital is posted as the first ledger entry.
         */
        post: operations["create_portfolio_api_portfolios_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolios/{portfolio_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Portfolio
         * @description Portfolio settings plus live cash, buying power and marked equity.
         */
        get: operations["get_portfolio_api_portfolios__portfolio_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolios/{portfolio_id}/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Orders
         * @description Orders newest first.
         */
        get: operations["list_orders_api_portfolios__portfolio_id__orders_get"];
        put?: never;
        /**
         * Place Order
         * @description Submit an order. A rejected order is returned with its reason rather than raising.
         */
        post: operations["place_order_api_portfolios__portfolio_id__orders_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolios/{portfolio_id}/orders/{order_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Cancel Order
         * @description Cancel an open order and release its cash reservation.
         */
        delete: operations["cancel_order_api_portfolios__portfolio_id__orders__order_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolios/{portfolio_id}/fills": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Fills
         * @description Executed fills newest first.
         */
        get: operations["list_fills_api_portfolios__portfolio_id__fills_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolios/{portfolio_id}/positions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Positions
         * @description Positions with market value and unrealized profit against the last known quote.
         */
        get: operations["list_positions_api_portfolios__portfolio_id__positions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolios/{portfolio_id}/ledger": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Ledger
         * @description The append-only cash record, newest first.
         */
        get: operations["list_ledger_api_portfolios__portfolio_id__ledger_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolios/{portfolio_id}/snapshots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Snapshots
         * @description The equity curve, oldest first.
         */
        get: operations["list_snapshots_api_portfolios__portfolio_id__snapshots_get"];
        put?: never;
        /**
         * Take Snapshot
         * @description Record today's equity point.
         */
        post: operations["take_snapshot_api_portfolios__portfolio_id__snapshots_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolios/{portfolio_id}/reconcile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run Reconciliation
         * @description Assert the projections still equal a replay of the ledger.
         */
        post: operations["run_reconciliation_api_portfolios__portfolio_id__reconcile_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolios/{portfolio_id}/strategy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Strategy
         * @description The strategy actually in force, with every default resolved.
         */
        get: operations["get_strategy_api_portfolios__portfolio_id__strategy_get"];
        /**
         * Update Strategy
         * @description Replace the strategy settings. Unknown keys inside a section are ignored, not rejected.
         */
        put: operations["update_strategy_api_portfolios__portfolio_id__strategy_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolios/{portfolio_id}/cycles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Cycles
         * @description Decision runs newest first.
         */
        get: operations["list_cycles_api_portfolios__portfolio_id__cycles_get"];
        put?: never;
        /**
         * Run Cycle
         * @description Run one decision cycle now. Serialized per portfolio against the scheduled run.
         */
        post: operations["run_cycle_api_portfolios__portfolio_id__cycles_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolios/{portfolio_id}/cycles/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Cycle
         * @description One run with its full reasoning: what was screened out, skipped, entered and exited.
         */
        get: operations["get_cycle_api_portfolios__portfolio_id__cycles__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolios/{portfolio_id}/strategy/preset/{preset_key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Apply Preset
         * @description Apply a preset wholesale. A starting point for the wizard, not a recommendation.
         */
        post: operations["apply_preset_api_portfolios__portfolio_id__strategy_preset__preset_key__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolios/{portfolio_id}/ai/calls": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Ai Calls
         * @description Every model call, newest first. The index for the "why did it buy this?" screen.
         */
        get: operations["list_ai_calls_api_portfolios__portfolio_id__ai_calls_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolios/{portfolio_id}/ai/calls/{call_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Ai Call
         * @description One call with its full prompt and raw response, exactly as sent and received.
         */
        get: operations["get_ai_call_api_portfolios__portfolio_id__ai_calls__call_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolios/{portfolio_id}/ai/spend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Ai Spend
         * @description Cost and token totals. Information for the dashboard, never a gate on a decision.
         */
        get: operations["get_ai_spend_api_portfolios__portfolio_id__ai_spend_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolios/{portfolio_id}/cycles/{run_id}/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Cycle Timeline
         * @description One decision cycle end to end: what the model asked for, what was clamped, what traded.
         *
         *     This is the screen that makes the guardrail diff a product feature rather than a claim.
         */
        get: operations["get_cycle_timeline_api_portfolios__portfolio_id__cycles__run_id__timeline_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolios/{portfolio_id}/ai/lessons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Lessons
         * @description Reflection memory: what the system learned from its own closed trades.
         */
        get: operations["list_lessons_api_portfolios__portfolio_id__ai_lessons_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolios/{portfolio_id}/ai/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Ai Summary
         * @description Whether the AI layer is on, and how often its judgement is being clamped.
         */
        get: operations["get_ai_summary_api_portfolios__portfolio_id__ai_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolios/{portfolio_id}/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Analyst Chat
         * @description Ask about this portfolio. Read-only: there is no path from here to the broker.
         */
        post: operations["analyst_chat_api_portfolios__portfolio_id__chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolios/{portfolio_id}/backtest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run Backtest
         * @description Replay the strategy and answer whether it beat holding an index fund.
         *
         *     The verdict is derived from the numbers, so a result that loses to the benchmark or fails
         *     deflation says so as the headline rather than as a footnote.
         */
        post: operations["run_backtest_api_portfolios__portfolio_id__backtest_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/engine/presets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Presets
         * @description The shipped strategy templates the configuration wizard offers.
         */
        get: operations["list_presets_api_engine_presets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/engine/schedule": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Schedule
         * @description The UTC cron jobs and when each next fires.
         */
        get: operations["get_schedule_api_engine_schedule_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Events
         * @description Recorded events for the current account, newest first.
         */
        get: operations["list_events_api_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream Events
         * @description Server-sent stream of live events for the current account.
         */
        get: operations["stream_events_api_events_stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AICallDetail
         * @description The full prompt and raw response. Stored verbatim so a decision can be re-read.
         */
        AICallDetail: {
            /** Id */
            id: number;
            /** Decision Run Id */
            decision_run_id: number | null;
            /** Correlation Id */
            correlation_id: string;
            /** Stage */
            stage: string;
            /** Model */
            model: string;
            /** Endpoint */
            endpoint: string;
            /** Rung */
            rung: string;
            /** Prompt Tokens */
            prompt_tokens: number;
            /** Completion Tokens */
            completion_tokens: number;
            /** Cached Tokens */
            cached_tokens: number;
            /** Latency Ms */
            latency_ms: number;
            /** Cost Usd */
            cost_usd: string;
            /** Brief Hash */
            brief_hash: string;
            /** Error */
            error: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** System Prompt */
            system_prompt: string;
            /** User Prompt */
            user_prompt: string;
            /** Response */
            response: string;
            /** Attempts */
            attempts: {
                [key: string]: unknown;
            };
        };
        /** AICallOut */
        AICallOut: {
            /** Id */
            id: number;
            /** Decision Run Id */
            decision_run_id: number | null;
            /** Correlation Id */
            correlation_id: string;
            /** Stage */
            stage: string;
            /** Model */
            model: string;
            /** Endpoint */
            endpoint: string;
            /** Rung */
            rung: string;
            /** Prompt Tokens */
            prompt_tokens: number;
            /** Completion Tokens */
            completion_tokens: number;
            /** Cached Tokens */
            cached_tokens: number;
            /** Latency Ms */
            latency_ms: number;
            /** Cost Usd */
            cost_usd: string;
            /** Brief Hash */
            brief_hash: string;
            /** Error */
            error: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** AISpend */
        AISpend: {
            /** Calls */
            calls: number;
            /** Cost Usd */
            cost_usd: string;
            /** Prompt Tokens */
            prompt_tokens: number;
            /** Completion Tokens */
            completion_tokens: number;
            /** Cached Tokens */
            cached_tokens: number;
        };
        /** BarOut */
        BarOut: {
            /**
             * Bar Date
             * Format: date
             */
            bar_date: string;
            /** Open */
            open: string;
            /** High */
            high: string;
            /** Low */
            low: string;
            /** Close */
            close: string;
            /** Volume */
            volume: string;
        };
        /** ChatMessage */
        ChatMessage: {
            /** Role */
            role: string;
            /** Content */
            content: string;
        };
        /** ChatReply */
        ChatReply: {
            /** Reply */
            reply: string;
            /** Grounded On */
            grounded_on: string[];
            /** Model */
            model: string;
            /** Cost Usd */
            cost_usd: string;
        };
        /** ChatRequest */
        ChatRequest: {
            /** Message */
            message: string;
            /**
             * History
             * @default []
             */
            history: components["schemas"]["ChatMessage"][];
        };
        /** CredentialCreate */
        CredentialCreate: {
            /** Provider Key */
            provider_key: string;
            /** Field */
            field: string;
            /** Secret */
            secret: string;
            /**
             * Label
             * @default default
             */
            label: string;
        };
        /**
         * CredentialOut
         * @description A stored credential. The secret itself is never returned — only a masked tail.
         */
        CredentialOut: {
            /** Id */
            id: number;
            /** Provider Key */
            provider_key: string;
            /** Field */
            field: string;
            /** Label */
            label: string;
            /** Masked */
            masked: string;
            /** Fingerprint */
            fingerprint: string;
            /** Key Id */
            key_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** CycleTimeline */
        CycleTimeline: {
            /** Run Id */
            run_id: number;
            /** Correlation Id */
            correlation_id: string;
            /**
             * As Of
             * Format: date
             */
            as_of: string;
            /** Status */
            status: string;
            /** Regime */
            regime: string;
            /** Exposure */
            exposure: string;
            /** Ai Enabled */
            ai_enabled: boolean;
            /** Ai Used */
            ai_used: boolean;
            /** Ai Reason */
            ai_reason: string;
            /** Strategy */
            strategy: string;
            /** Rounds */
            rounds: number;
            /** Brief Hash */
            brief_hash: string;
            /** Confidence */
            confidence: {
                [key: string]: number;
            };
            /** Guardrail */
            guardrail: components["schemas"]["GuardrailRow"][];
            /** Analysts Skipped */
            analysts_skipped: {
                [key: string]: string;
            };
            /** Entries */
            entries: {
                [key: string]: unknown;
            }[];
            /** Exits */
            exits: {
                [key: string]: unknown;
            }[];
            /** Screened Out */
            screened_out: {
                [key: string]: string;
            };
            /** Skipped */
            skipped: {
                [key: string]: string;
            };
            /** Calls */
            calls: components["schemas"]["AICallOut"][];
        };
        /** CycleTriggered */
        CycleTriggered: {
            /** Run Id */
            run_id: number;
            /** Correlation Id */
            correlation_id: string;
            /**
             * As Of
             * Format: date
             */
            as_of: string;
            /** Status */
            status: string;
            /** Orders Placed */
            orders_placed: number;
            /** Entries */
            entries: number;
            /** Exits */
            exits: number;
            /** Regime */
            regime: string;
            /** Error */
            error?: string | null;
        };
        /** DecisionRunDetail */
        DecisionRunDetail: {
            /** Id */
            id: number;
            /** Correlation Id */
            correlation_id: string;
            /** Trigger */
            trigger: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Finished At */
            finished_at: string | null;
            /**
             * As Of
             * Format: date
             */
            as_of: string;
            /** Status */
            status: string;
            /** Regime */
            regime: string;
            /** Exposure */
            exposure: string;
            /** Candidates */
            candidates: number;
            /** Entries */
            entries: number;
            /** Exits */
            exits: number;
            /** Orders Placed */
            orders_placed: number;
            /** Error */
            error: string | null;
            /** Detail */
            detail: {
                [key: string]: unknown;
            };
        };
        /** DecisionRunOut */
        DecisionRunOut: {
            /** Id */
            id: number;
            /** Correlation Id */
            correlation_id: string;
            /** Trigger */
            trigger: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Finished At */
            finished_at: string | null;
            /**
             * As Of
             * Format: date
             */
            as_of: string;
            /** Status */
            status: string;
            /** Regime */
            regime: string;
            /** Exposure */
            exposure: string;
            /** Candidates */
            candidates: number;
            /** Entries */
            entries: number;
            /** Exits */
            exits: number;
            /** Orders Placed */
            orders_placed: number;
            /** Error */
            error: string | null;
        };
        /** EventOut */
        EventOut: {
            /** Id */
            id: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Domain */
            domain: string;
            /** Kind */
            kind: string;
            /** Severity */
            severity: string;
            /** Portfolio Id */
            portfolio_id: number | null;
            /** Correlation Id */
            correlation_id: string | null;
            /** Message */
            message: string | null;
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
        };
        /** FillOut */
        FillOut: {
            /** Id */
            id: number;
            /** Order Id */
            order_id: number;
            /** Seq */
            seq: number;
            /** Qty */
            qty: string;
            /** Price */
            price: string;
            /** Fee */
            fee: string;
            /** Slippage Amount */
            slippage_amount: string;
            /**
             * Executed At
             * Format: date-time
             */
            executed_at: string;
        };
        /** GuardrailRow */
        GuardrailRow: {
            /** Symbol */
            symbol: string;
            /** Reason */
            reason: string;
            /** Asked */
            asked: string;
            /** Applied */
            applied: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /** Status */
            status: string;
            /** Env */
            env: string;
            /** Database */
            database: string;
        };
        /** InstrumentOut */
        InstrumentOut: {
            /** Id */
            id: number;
            /** Symbol */
            symbol: string;
            /** Asset Class */
            asset_class: string;
            /** Name */
            name: string;
            /** Exchange */
            exchange: string;
            /** Sector */
            sector: string;
            /** Currency */
            currency: string;
            /** Is Active */
            is_active: boolean;
            /** First Bar Date */
            first_bar_date: string | null;
            /** Last Bar Date */
            last_bar_date: string | null;
            /** Last Quote At */
            last_quote_at: string | null;
            /** Last Quote Price */
            last_quote_price: string | null;
            /** Last Quote Source */
            last_quote_source: string | null;
            /** Staleness Seconds */
            staleness_seconds?: number | null;
        };
        /** LedgerEntryOut */
        LedgerEntryOut: {
            /** Id */
            id: number;
            /**
             * At
             * Format: date-time
             */
            at: string;
            /** Entry Type */
            entry_type: string;
            /** Amount */
            amount: string;
            /** Balance After */
            balance_after: string;
            /** Ref Type */
            ref_type: string | null;
            /** Ref Id */
            ref_id: number | null;
            /** Memo */
            memo: string | null;
        };
        /** LessonOut */
        LessonOut: {
            /** Id */
            id: number;
            /** Symbol */
            symbol: string;
            /**
             * Closed At
             * Format: date-time
             */
            closed_at: string;
            /** Holding Days */
            holding_days: number;
            /** Realized Return */
            realized_return: string;
            /** Benchmark Return */
            benchmark_return: string;
            /** Alpha */
            alpha: string;
            /** Text */
            text: string;
        };
        /** LoginRequest */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** OrderCreate */
        OrderCreate: {
            /** Symbol */
            symbol: string;
            /** Side */
            side: string;
            /** Qty */
            qty: number | string;
            /**
             * Order Type
             * @default MARKET
             */
            order_type: string;
            /**
             * Time In Force
             * @default DAY
             */
            time_in_force: string;
            /** Limit Price */
            limit_price?: number | string | null;
            /** Stop Price */
            stop_price?: number | string | null;
            /** Client Order Id */
            client_order_id?: string | null;
        };
        /** OrderOut */
        OrderOut: {
            /** Id */
            id: number;
            /** Client Order Id */
            client_order_id: string;
            /** Instrument Id */
            instrument_id: number;
            /** Side */
            side: string;
            /** Order Type */
            order_type: string;
            /** Time In Force */
            time_in_force: string;
            /** Qty */
            qty: string;
            /** Limit Price */
            limit_price: string | null;
            /** Stop Price */
            stop_price: string | null;
            /** Status */
            status: string;
            /** Filled Qty */
            filled_qty: string;
            /** Avg Fill Price */
            avg_fill_price: string | null;
            /** Reserved Cash */
            reserved_cash: string;
            /** Reject Reason */
            reject_reason: string | null;
            /** Submitted At */
            submitted_at: string | null;
            /** Closed At */
            closed_at: string | null;
        };
        /** PortfolioCreate */
        PortfolioCreate: {
            /** Name */
            name: string;
            /** Initial Capital */
            initial_capital: number | string;
            /**
             * Slippage Bps
             * @default 10
             */
            slippage_bps: number | string;
            /**
             * Commission Bps
             * @default 0
             */
            commission_bps: number | string;
            /**
             * Min Commission
             * @default 0
             */
            min_commission: number | string;
            /**
             * Allow Fractional
             * @default false
             */
            allow_fractional: boolean;
        };
        /** PortfolioDetail */
        PortfolioDetail: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Base Currency */
            base_currency: string;
            /** Is Active */
            is_active: boolean;
            /** Initial Capital */
            initial_capital: string;
            /** Slippage Bps */
            slippage_bps: string;
            /** Commission Bps */
            commission_bps: string;
            /** Allow Fractional */
            allow_fractional: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Cash */
            cash: string;
            /** Reserved */
            reserved: string;
            /** Buying Power */
            buying_power: string;
            /** Equity */
            equity: string;
            /** Open Positions */
            open_positions: number;
        };
        /** PortfolioOut */
        PortfolioOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Base Currency */
            base_currency: string;
            /** Is Active */
            is_active: boolean;
            /** Initial Capital */
            initial_capital: string;
            /** Slippage Bps */
            slippage_bps: string;
            /** Commission Bps */
            commission_bps: string;
            /** Allow Fractional */
            allow_fractional: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** PositionOut */
        PositionOut: {
            /** Id */
            id: number;
            /** Instrument Id */
            instrument_id: number;
            /** Status */
            status: string;
            /** Qty */
            qty: string;
            /** Avg Cost */
            avg_cost: string;
            /** Realized Pnl */
            realized_pnl: string;
            /** Fees Paid */
            fees_paid: string;
            /**
             * Opened At
             * Format: date-time
             */
            opened_at: string;
            /** Closed At */
            closed_at: string | null;
            /** Market Value */
            market_value?: string | null;
            /** Unrealized Pnl */
            unrealized_pnl?: string | null;
        };
        /**
         * ProviderStatusOut
         * @description What the provider-health dashboard renders. Never contains a credential value.
         */
        ProviderStatusOut: {
            /** Provider */
            provider: string;
            /** Label */
            label: string;
            /** Keyless */
            keyless: boolean;
            /** Configured */
            configured: boolean;
            /** Available */
            available: boolean;
            /** Capabilities */
            capabilities: string[];
            /** Asset Classes */
            asset_classes: string[];
            /** Missing Credentials */
            missing_credentials: string[];
            /** Fields */
            fields: {
                [key: string]: string;
            }[];
            /** Health */
            health: {
                [key: string]: unknown;
            };
        };
        /** QuoteOut */
        QuoteOut: {
            /** Symbol */
            symbol: string;
            /** Price */
            price: string;
            /**
             * At
             * Format: date-time
             */
            at: string;
            /** Previous Close */
            previous_close?: string | null;
            /** Bid */
            bid?: string | null;
            /** Ask */
            ask?: string | null;
            /** Volume */
            volume?: string | null;
        };
        /** ReconciliationOut */
        ReconciliationOut: {
            /** Portfolio Id */
            portfolio_id: number;
            /** Ok */
            ok: boolean;
            /** Cash */
            cash: string;
            /** Problems */
            problems: string[];
        };
        /** RegisterRequest */
        RegisterRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /** Display Name */
            display_name: string;
        };
        /** ScheduledJob */
        ScheduledJob: {
            /** Id */
            id: string;
            /** Cron */
            cron: string;
            /** Next Run */
            next_run: string | null;
        };
        /** SnapshotOut */
        SnapshotOut: {
            /**
             * Snap Date
             * Format: date
             */
            snap_date: string;
            /** Equity */
            equity: string;
            /** Cash */
            cash: string;
            /** Positions Value */
            positions_value: string;
            /** Realized Pnl */
            realized_pnl: string;
            /** Unrealized Pnl */
            unrealized_pnl: string;
            /** Open Positions */
            open_positions: number;
            /** Drawdown Pct */
            drawdown_pct: string;
        };
        /** StrategySettings */
        StrategySettings: {
            /**
             * Benchmark
             * @default SPY
             */
            benchmark: string;
            /**
             * Cadence
             * @default daily
             */
            cadence: string;
            /**
             * Autopilot
             * @default false
             */
            autopilot: boolean;
            /** Strategy */
            strategy?: {
                [key: string]: unknown;
            };
            /** Universe */
            universe?: {
                [key: string]: unknown;
            };
        };
        /** StrategySummary */
        StrategySummary: {
            /** Benchmark */
            benchmark: string;
            /** Cadence */
            cadence: string;
            /** Autopilot */
            autopilot: boolean;
            /** Parameter Count */
            parameter_count: number;
            /** Screen */
            screen: {
                [key: string]: unknown;
            };
            /** Sizing */
            sizing: {
                [key: string]: unknown;
            };
            /** Regime */
            regime: {
                [key: string]: unknown;
            };
            /** Exits */
            exits: {
                [key: string]: unknown;
            };
            /** Turnover */
            turnover: {
                [key: string]: unknown;
            };
            /** Costs */
            costs: {
                [key: string]: unknown;
            };
        };
        /** SyncRequest */
        SyncRequest: {
            /** Asset Class */
            asset_class: string;
            /**
             * Limit
             * @default 200
             */
            limit: number;
            /**
             * Refresh Bars
             * @default false
             */
            refresh_bars: boolean;
        };
        /** SyncResultOut */
        SyncResultOut: {
            /** Asset Class */
            asset_class: string;
            /** Instruments */
            instruments: number;
            /** Bars Written */
            bars_written: number;
            /** Skipped Fresh */
            skipped_fresh: number;
            /** Failed */
            failed: string[];
            /** Gaps */
            gaps: {
                [key: string]: number;
            };
        };
        /** TokenResponse */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            /** Expires In */
            expires_in: number;
        };
        /** UserOut */
        UserOut: {
            /** Id */
            id: number;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Display Name */
            display_name: string;
            /** Is Admin */
            is_admin: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Last Login At */
            last_login_at: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    register_api_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_api_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
        };
    };
    logout_api_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_api_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
        };
    };
    list_credentials_api_credentials_get: {
        parameters: {
            query?: {
                provider_key?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CredentialOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    store_api_credentials_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CredentialCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CredentialOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_credential_api_credentials__credential_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                credential_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_instruments_api_market_instruments_get: {
        parameters: {
            query?: {
                asset_class?: string | null;
                active_only?: boolean;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstrumentOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    instrument_bars_api_market_instruments__symbol__bars_get: {
        parameters: {
            query?: {
                asset_class?: string | null;
                limit?: number;
            };
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BarOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    quotes_api_market_quotes_get: {
        parameters: {
            query: {
                /** @description Comma separated symbols */
                symbols: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuoteOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    providers_api_market_providers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderStatusOut"][];
                };
            };
        };
    };
    sync_api_market_sync_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SyncRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncResultOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_portfolios_api_portfolios_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioOut"][];
                };
            };
        };
    };
    create_portfolio_api_portfolios_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PortfolioCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_portfolio_api_portfolios__portfolio_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                portfolio_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_orders_api_portfolios__portfolio_id__orders_get: {
        parameters: {
            query?: {
                open_only?: boolean;
                limit?: number;
            };
            header?: never;
            path: {
                portfolio_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    place_order_api_portfolios__portfolio_id__orders_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                portfolio_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrderCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_order_api_portfolios__portfolio_id__orders__order_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                portfolio_id: number;
                order_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_fills_api_portfolios__portfolio_id__fills_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                portfolio_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FillOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_positions_api_portfolios__portfolio_id__positions_get: {
        parameters: {
            query?: {
                open_only?: boolean;
            };
            header?: never;
            path: {
                portfolio_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PositionOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_ledger_api_portfolios__portfolio_id__ledger_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                portfolio_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LedgerEntryOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_snapshots_api_portfolios__portfolio_id__snapshots_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                portfolio_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapshotOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    take_snapshot_api_portfolios__portfolio_id__snapshots_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                portfolio_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapshotOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_reconciliation_api_portfolios__portfolio_id__reconcile_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                portfolio_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReconciliationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_strategy_api_portfolios__portfolio_id__strategy_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                portfolio_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategySummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_strategy_api_portfolios__portfolio_id__strategy_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                portfolio_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StrategySettings"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategySummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_cycles_api_portfolios__portfolio_id__cycles_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                portfolio_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecisionRunOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_cycle_api_portfolios__portfolio_id__cycles_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                portfolio_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CycleTriggered"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_cycle_api_portfolios__portfolio_id__cycles__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                portfolio_id: number;
                run_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecisionRunDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    apply_preset_api_portfolios__portfolio_id__strategy_preset__preset_key__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                portfolio_id: number;
                preset_key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategySummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_ai_calls_api_portfolios__portfolio_id__ai_calls_get: {
        parameters: {
            query?: {
                stage?: string | null;
                limit?: number;
            };
            header?: never;
            path: {
                portfolio_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AICallOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_ai_call_api_portfolios__portfolio_id__ai_calls__call_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                portfolio_id: number;
                call_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AICallDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_ai_spend_api_portfolios__portfolio_id__ai_spend_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                portfolio_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AISpend"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_cycle_timeline_api_portfolios__portfolio_id__cycles__run_id__timeline_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                portfolio_id: number;
                run_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CycleTimeline"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_lessons_api_portfolios__portfolio_id__ai_lessons_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                portfolio_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LessonOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_ai_summary_api_portfolios__portfolio_id__ai_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                portfolio_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyst_chat_api_portfolios__portfolio_id__chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                portfolio_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatReply"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_backtest_api_portfolios__portfolio_id__backtest_post: {
        parameters: {
            query?: {
                start?: string | null;
                end?: string | null;
                control?: boolean;
            };
            header?: never;
            path: {
                portfolio_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_presets_api_engine_presets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
        };
    };
    get_schedule_api_engine_schedule_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduledJob"][];
                };
            };
        };
    };
    list_events_api_events_get: {
        parameters: {
            query?: {
                domain?: string | null;
                kind?: string | null;
                severity?: string | null;
                correlation_id?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_events_api_events_stream_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
