"""credential slot is unique per field

Revision ID: 0f12908ad343
Revises: ae1174a68062
Create Date: 2026-08-15 14:01:45.632135+00:00

"""

from collections.abc import Sequence

from alembic import op


revision: str = "0f12908ad343"
down_revision: str | Sequence[str] | None = "ae1174a68062"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("credentials", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("uq_credential_slot"), type_="unique")
        batch_op.create_unique_constraint(
            "uq_credential_slot", ["user_id", "provider_key", "field", "label"]
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("credentials", schema=None) as batch_op:
        batch_op.drop_constraint("uq_credential_slot", type_="unique")
        batch_op.create_unique_constraint(
            batch_op.f("uq_credential_slot"), ["user_id", "provider_key", "label"]
        )

    # ### end Alembic commands ###
