"""Add reusable model profiles

Revision ID: 1aa283dbe2ea
Revises: f308c69dc911
Create Date: 2026-08-16 08:04:44.048673+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import tradebot.db.base


revision: str = "1aa283dbe2ea"
down_revision: str | Sequence[str] | None = "f308c69dc911"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "model_profiles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("endpoints", sa.JSON(), nullable=False),
        sa.Column("quality", sa.String(length=16), nullable=False),
        sa.Column("deliberation", sa.String(length=32), nullable=False),
        sa.Column("created_at", tradebot.db.base.UtcDateTime(timezone=True), nullable=False),
        sa.Column("updated_at", tradebot.db.base.UtcDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_model_profiles_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_model_profiles")),
        sa.UniqueConstraint("user_id", "name", name="uq_model_profile_name"),
    )
    with op.batch_alter_table("model_profiles", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_model_profiles_user_id"), ["user_id"], unique=False)

    with op.batch_alter_table("portfolios", schema=None) as batch_op:
        batch_op.add_column(sa.Column("model_profile_id", sa.Integer(), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_portfolios_model_profile_id"), ["model_profile_id"], unique=False
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_portfolios_model_profile_id_model_profiles"),
            "model_profiles",
            ["model_profile_id"],
            ["id"],
            ondelete="SET NULL",
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("portfolios", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_portfolios_model_profile_id_model_profiles"), type_="foreignkey"
        )
        batch_op.drop_index(batch_op.f("ix_portfolios_model_profile_id"))
        batch_op.drop_column("model_profile_id")

    with op.batch_alter_table("model_profiles", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_model_profiles_user_id"))

    op.drop_table("model_profiles")
    # ### end Alembic commands ###
