"""Add strategy config, position stop state and decision runs

Revision ID: 4880702a7da0
Revises: 932609eb0557
Create Date: 2026-08-15 19:50:59.788791+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import tradebot.db.base


revision: str = "4880702a7da0"
down_revision: str | Sequence[str] | None = "932609eb0557"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "decision_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("portfolio_id", sa.Integer(), nullable=False),
        sa.Column("correlation_id", sa.String(length=36), nullable=False),
        sa.Column("trigger", sa.String(length=24), nullable=False),
        sa.Column("started_at", tradebot.db.base.UtcDateTime(timezone=True), nullable=False),
        sa.Column("finished_at", tradebot.db.base.UtcDateTime(timezone=True), nullable=True),
        sa.Column("as_of", sa.Date(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("regime", sa.String(length=16), nullable=False),
        sa.Column("exposure", sa.Numeric(precision=10, scale=4), nullable=False),
        sa.Column("candidates", sa.Integer(), nullable=False),
        sa.Column("entries", sa.Integer(), nullable=False),
        sa.Column("exits", sa.Integer(), nullable=False),
        sa.Column("orders_placed", sa.Integer(), nullable=False),
        sa.Column("detail", sa.JSON(), nullable=False),
        sa.Column("error", sa.String(length=500), nullable=True),
        sa.ForeignKeyConstraint(
            ["portfolio_id"],
            ["portfolios.id"],
            name=op.f("fk_decision_runs_portfolio_id_portfolios"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_decision_runs")),
    )
    with op.batch_alter_table("decision_runs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_decision_runs_correlation_id"), ["correlation_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_decision_runs_portfolio_id"), ["portfolio_id"], unique=False
        )
        batch_op.create_index(
            "ix_decision_runs_portfolio_started", ["portfolio_id", "started_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_decision_runs_started_at"), ["started_at"], unique=False
        )

    with op.batch_alter_table("portfolios", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("benchmark", sa.String(length=32), nullable=False, server_default="SPY")
        )
        batch_op.add_column(
            sa.Column("cadence", sa.String(length=32), nullable=False, server_default="daily")
        )
        batch_op.add_column(
            sa.Column("autopilot", sa.Boolean(), nullable=False, server_default=sa.false())
        )
        batch_op.add_column(sa.Column("strategy", sa.JSON(), nullable=False, server_default="{}"))
        batch_op.add_column(sa.Column("universe", sa.JSON(), nullable=False, server_default="{}"))

    with op.batch_alter_table("positions", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("stop_price", sa.Numeric(precision=20, scale=8), nullable=True)
        )
        batch_op.add_column(
            sa.Column("highest_close", sa.Numeric(precision=20, scale=8), nullable=True)
        )
        batch_op.add_column(
            sa.Column("laddered", sa.Boolean(), nullable=False, server_default=sa.false())
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("positions", schema=None) as batch_op:
        batch_op.drop_column("laddered")
        batch_op.drop_column("highest_close")
        batch_op.drop_column("stop_price")

    with op.batch_alter_table("portfolios", schema=None) as batch_op:
        batch_op.drop_column("universe")
        batch_op.drop_column("strategy")
        batch_op.drop_column("autopilot")
        batch_op.drop_column("cadence")
        batch_op.drop_column("benchmark")

    with op.batch_alter_table("decision_runs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_decision_runs_started_at"))
        batch_op.drop_index("ix_decision_runs_portfolio_started")
        batch_op.drop_index(batch_op.f("ix_decision_runs_portfolio_id"))
        batch_op.drop_index(batch_op.f("ix_decision_runs_correlation_id"))

    op.drop_table("decision_runs")
    # ### end Alembic commands ###
