"""paper broker: ledger, orders, fills, lots, positions

Revision ID: 932609eb0557
Revises: 0f12908ad343
Create Date: 2026-08-15 18:57:10.614236+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import tradebot.db.base


revision: str = "932609eb0557"
down_revision: str | Sequence[str] | None = "0f12908ad343"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "portfolios",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("base_currency", sa.String(length=8), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("initial_capital", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("slippage_bps", sa.Numeric(precision=10, scale=4), nullable=False),
        sa.Column("commission_bps", sa.Numeric(precision=10, scale=4), nullable=False),
        sa.Column("min_commission", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("allow_fractional", sa.Boolean(), nullable=False),
        sa.Column("created_at", tradebot.db.base.UtcDateTime(timezone=True), nullable=False),
        sa.Column("updated_at", tradebot.db.base.UtcDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_portfolios_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_portfolios")),
        sa.UniqueConstraint("user_id", "name", name="uq_portfolio_name"),
    )
    with op.batch_alter_table("portfolios", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_portfolios_user_id"), ["user_id"], unique=False)

    op.create_table(
        "ledger_entries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("portfolio_id", sa.Integer(), nullable=False),
        sa.Column("at", tradebot.db.base.UtcDateTime(timezone=True), nullable=False),
        sa.Column("entry_type", sa.String(length=16), nullable=False),
        sa.Column("amount", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("balance_after", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("ref_type", sa.String(length=16), nullable=True),
        sa.Column("ref_id", sa.Integer(), nullable=True),
        sa.Column("memo", sa.String(length=200), nullable=True),
        sa.ForeignKeyConstraint(
            ["portfolio_id"],
            ["portfolios.id"],
            name=op.f("fk_ledger_entries_portfolio_id_portfolios"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ledger_entries")),
    )
    with op.batch_alter_table("ledger_entries", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_ledger_entries_at"), ["at"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_ledger_entries_portfolio_id"), ["portfolio_id"], unique=False
        )
        batch_op.create_index("ix_ledger_portfolio_seq", ["portfolio_id", "id"], unique=False)

    op.create_table(
        "orders",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("portfolio_id", sa.Integer(), nullable=False),
        sa.Column("instrument_id", sa.Integer(), nullable=False),
        sa.Column("client_order_id", sa.String(length=64), nullable=False),
        sa.Column("side", sa.String(length=4), nullable=False),
        sa.Column("order_type", sa.String(length=12), nullable=False),
        sa.Column("time_in_force", sa.String(length=4), nullable=False),
        sa.Column("qty", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("limit_price", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("stop_price", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("filled_qty", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("avg_fill_price", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("reserved_cash", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("submitted_at", tradebot.db.base.UtcDateTime(timezone=True), nullable=True),
        sa.Column("expires_at", tradebot.db.base.UtcDateTime(timezone=True), nullable=True),
        sa.Column("closed_at", tradebot.db.base.UtcDateTime(timezone=True), nullable=True),
        sa.Column("reject_reason", sa.String(length=200), nullable=True),
        sa.Column("created_at", tradebot.db.base.UtcDateTime(timezone=True), nullable=False),
        sa.Column("updated_at", tradebot.db.base.UtcDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instruments.id"],
            name=op.f("fk_orders_instrument_id_instruments"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["portfolio_id"],
            ["portfolios.id"],
            name=op.f("fk_orders_portfolio_id_portfolios"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_orders")),
        sa.UniqueConstraint("client_order_id", name="uq_order_client_id"),
    )
    with op.batch_alter_table("orders", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_orders_instrument_id"), ["instrument_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_orders_portfolio_id"), ["portfolio_id"], unique=False)
        batch_op.create_index(
            "ix_orders_portfolio_status", ["portfolio_id", "status"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_orders_status"), ["status"], unique=False)

    op.create_table(
        "portfolio_snapshots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("portfolio_id", sa.Integer(), nullable=False),
        sa.Column("snap_date", sa.Date(), nullable=False),
        sa.Column("equity", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("cash", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("positions_value", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("realized_pnl", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("unrealized_pnl", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("open_positions", sa.Integer(), nullable=False),
        sa.Column("drawdown_pct", sa.Numeric(precision=10, scale=4), nullable=False),
        sa.ForeignKeyConstraint(
            ["portfolio_id"],
            ["portfolios.id"],
            name=op.f("fk_portfolio_snapshots_portfolio_id_portfolios"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_portfolio_snapshots")),
        sa.UniqueConstraint("portfolio_id", "snap_date", name="uq_snapshot_day"),
    )
    with op.batch_alter_table("portfolio_snapshots", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_portfolio_snapshots_portfolio_id"), ["portfolio_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_portfolio_snapshots_snap_date"), ["snap_date"], unique=False
        )

    op.create_table(
        "positions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("portfolio_id", sa.Integer(), nullable=False),
        sa.Column("instrument_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=8), nullable=False),
        sa.Column("qty", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("avg_cost", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("realized_pnl", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("fees_paid", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("opened_at", tradebot.db.base.UtcDateTime(timezone=True), nullable=False),
        sa.Column("closed_at", tradebot.db.base.UtcDateTime(timezone=True), nullable=True),
        sa.Column("created_at", tradebot.db.base.UtcDateTime(timezone=True), nullable=False),
        sa.Column("updated_at", tradebot.db.base.UtcDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instruments.id"],
            name=op.f("fk_positions_instrument_id_instruments"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["portfolio_id"],
            ["portfolios.id"],
            name=op.f("fk_positions_portfolio_id_portfolios"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_positions")),
        sa.UniqueConstraint("portfolio_id", "instrument_id", "status", name="uq_open_position"),
    )
    with op.batch_alter_table("positions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_positions_instrument_id"), ["instrument_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_positions_portfolio_id"), ["portfolio_id"], unique=False
        )
        batch_op.create_index(
            "ix_positions_portfolio_status", ["portfolio_id", "status"], unique=False
        )

    op.create_table(
        "fills",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("order_id", sa.Integer(), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("qty", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("price", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("fee", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("slippage_amount", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("executed_at", tradebot.db.base.UtcDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["order_id"], ["orders.id"], name=op.f("fk_fills_order_id_orders"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fills")),
        sa.UniqueConstraint("order_id", "seq", name="uq_fill_seq"),
    )
    with op.batch_alter_table("fills", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_fills_executed_at"), ["executed_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_fills_order_id"), ["order_id"], unique=False)

    op.create_table(
        "lots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("position_id", sa.Integer(), nullable=False),
        sa.Column("fill_id", sa.Integer(), nullable=True),
        sa.Column("qty_original", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("qty_open", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("cost_basis", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("fee_paid", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("opened_at", tradebot.db.base.UtcDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["fill_id"], ["fills.id"], name=op.f("fk_lots_fill_id_fills"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["position_id"],
            ["positions.id"],
            name=op.f("fk_lots_position_id_positions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_lots")),
    )
    with op.batch_alter_table("lots", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_lots_opened_at"), ["opened_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_lots_position_id"), ["position_id"], unique=False)
        batch_op.create_index("ix_lots_position_opened", ["position_id", "opened_at"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("lots", schema=None) as batch_op:
        batch_op.drop_index("ix_lots_position_opened")
        batch_op.drop_index(batch_op.f("ix_lots_position_id"))
        batch_op.drop_index(batch_op.f("ix_lots_opened_at"))

    op.drop_table("lots")
    with op.batch_alter_table("fills", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_fills_order_id"))
        batch_op.drop_index(batch_op.f("ix_fills_executed_at"))

    op.drop_table("fills")
    with op.batch_alter_table("positions", schema=None) as batch_op:
        batch_op.drop_index("ix_positions_portfolio_status")
        batch_op.drop_index(batch_op.f("ix_positions_portfolio_id"))
        batch_op.drop_index(batch_op.f("ix_positions_instrument_id"))

    op.drop_table("positions")
    with op.batch_alter_table("portfolio_snapshots", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_portfolio_snapshots_snap_date"))
        batch_op.drop_index(batch_op.f("ix_portfolio_snapshots_portfolio_id"))

    op.drop_table("portfolio_snapshots")
    with op.batch_alter_table("orders", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_orders_status"))
        batch_op.drop_index("ix_orders_portfolio_status")
        batch_op.drop_index(batch_op.f("ix_orders_portfolio_id"))
        batch_op.drop_index(batch_op.f("ix_orders_instrument_id"))

    op.drop_table("orders")
    with op.batch_alter_table("ledger_entries", schema=None) as batch_op:
        batch_op.drop_index("ix_ledger_portfolio_seq")
        batch_op.drop_index(batch_op.f("ix_ledger_entries_portfolio_id"))
        batch_op.drop_index(batch_op.f("ix_ledger_entries_at"))

    op.drop_table("ledger_entries")
    with op.batch_alter_table("portfolios", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_portfolios_user_id"))

    op.drop_table("portfolios")
    # ### end Alembic commands ###
