"""market data: instruments, bars, corporate actions

Revision ID: ae1174a68062
Revises: b2aa18a4cc1a
Create Date: 2026-08-15 12:05:29.269774+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import tradebot.db.base


revision: str = "ae1174a68062"
down_revision: str | Sequence[str] | None = "b2aa18a4cc1a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "instruments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column("asset_class", sa.String(length=16), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("exchange", sa.String(length=32), nullable=False),
        sa.Column("sector", sa.String(length=64), nullable=False),
        sa.Column("currency", sa.String(length=8), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("first_bar_date", sa.Date(), nullable=True),
        sa.Column("last_bar_date", sa.Date(), nullable=True),
        sa.Column("last_quote_at", tradebot.db.base.UtcDateTime(timezone=True), nullable=True),
        sa.Column("last_quote_price", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("last_quote_source", sa.String(length=32), nullable=True),
        sa.Column("extra", sa.JSON(), nullable=False),
        sa.Column("created_at", tradebot.db.base.UtcDateTime(timezone=True), nullable=False),
        sa.Column("updated_at", tradebot.db.base.UtcDateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_instruments")),
        sa.UniqueConstraint("symbol", "asset_class", name="uq_instrument_symbol_class"),
    )
    with op.batch_alter_table("instruments", schema=None) as batch_op:
        batch_op.create_index("ix_instruments_active", ["asset_class", "is_active"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_instruments_asset_class"), ["asset_class"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_instruments_symbol"), ["symbol"], unique=False)

    op.create_table(
        "provider_usage",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("provider_key", sa.String(length=32), nullable=False),
        sa.Column("usage_date", sa.Date(), nullable=False),
        sa.Column("requests", sa.Integer(), nullable=False),
        sa.Column("errors", sa.Integer(), nullable=False),
        sa.Column("rate_limited", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_provider_usage")),
        sa.UniqueConstraint("provider_key", "usage_date", name="uq_provider_usage_day"),
    )
    with op.batch_alter_table("provider_usage", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_provider_usage_provider_key"), ["provider_key"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_provider_usage_usage_date"), ["usage_date"], unique=False
        )

    op.create_table(
        "corporate_actions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("instrument_id", sa.Integer(), nullable=False),
        sa.Column("effective_date", sa.Date(), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("split_ratio", sa.Numeric(precision=18, scale=8), nullable=True),
        sa.Column("cash_amount", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("applied_at", tradebot.db.base.UtcDateTime(timezone=True), nullable=True),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("created_at", tradebot.db.base.UtcDateTime(timezone=True), nullable=False),
        sa.Column("updated_at", tradebot.db.base.UtcDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instruments.id"],
            name=op.f("fk_corporate_actions_instrument_id_instruments"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_corporate_actions")),
        sa.UniqueConstraint("instrument_id", "effective_date", "kind", name="uq_corporate_action"),
    )
    with op.batch_alter_table("corporate_actions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_corporate_actions_effective_date"), ["effective_date"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_corporate_actions_instrument_id"), ["instrument_id"], unique=False
        )

    op.create_table(
        "price_bars",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("instrument_id", sa.Integer(), nullable=False),
        sa.Column("bar_date", sa.Date(), nullable=False),
        sa.Column("open", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("high", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("low", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("close", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("volume", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("adjusted", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instruments.id"],
            name=op.f("fk_price_bars_instrument_id_instruments"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_price_bars")),
        sa.UniqueConstraint("instrument_id", "bar_date", name="uq_bar_instrument_date"),
    )
    with op.batch_alter_table("price_bars", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_price_bars_bar_date"), ["bar_date"], unique=False)
        batch_op.create_index(
            "ix_price_bars_instrument_date", ["instrument_id", "bar_date"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_price_bars_instrument_id"), ["instrument_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("price_bars", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_price_bars_instrument_id"))
        batch_op.drop_index("ix_price_bars_instrument_date")
        batch_op.drop_index(batch_op.f("ix_price_bars_bar_date"))

    op.drop_table("price_bars")
    with op.batch_alter_table("corporate_actions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_corporate_actions_instrument_id"))
        batch_op.drop_index(batch_op.f("ix_corporate_actions_effective_date"))

    op.drop_table("corporate_actions")
    with op.batch_alter_table("provider_usage", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_provider_usage_usage_date"))
        batch_op.drop_index(batch_op.f("ix_provider_usage_provider_key"))

    op.drop_table("provider_usage")
    with op.batch_alter_table("instruments", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_instruments_symbol"))
        batch_op.drop_index(batch_op.f("ix_instruments_asset_class"))
        batch_op.drop_index("ix_instruments_active")

    op.drop_table("instruments")
    # ### end Alembic commands ###
