"""baseline schema

Revision ID: b2aa18a4cc1a
Revises:
Create Date: 2026-08-15 15:25:24.951342

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import tradebot.db.base


revision: str = "b2aa18a4cc1a"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=120), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_admin", sa.Boolean(), nullable=False),
        sa.Column("last_login_at", tradebot.db.base.UtcDateTime(timezone=True), nullable=True),
        sa.Column("created_at", tradebot.db.base.UtcDateTime(timezone=True), nullable=False),
        sa.Column("updated_at", tradebot.db.base.UtcDateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_email"), ["email"], unique=True)

    op.create_table(
        "credentials",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("provider_key", sa.String(length=64), nullable=False),
        sa.Column("field", sa.String(length=64), nullable=False),
        sa.Column("label", sa.String(length=120), nullable=False),
        sa.Column("wrapped_key", sa.LargeBinary(), nullable=False),
        sa.Column("nonce", sa.LargeBinary(), nullable=False),
        sa.Column("ciphertext", sa.LargeBinary(), nullable=False),
        sa.Column("key_id", sa.String(length=32), nullable=False),
        sa.Column("masked", sa.String(length=32), nullable=False),
        sa.Column("fingerprint", sa.String(length=24), nullable=False),
        sa.Column("created_at", tradebot.db.base.UtcDateTime(timezone=True), nullable=False),
        sa.Column("updated_at", tradebot.db.base.UtcDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_credentials_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_credentials")),
        sa.UniqueConstraint("user_id", "provider_key", "label", name="uq_credential_slot"),
    )
    with op.batch_alter_table("credentials", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_credentials_provider_key"), ["provider_key"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_credentials_user_id"), ["user_id"], unique=False)

    op.create_table(
        "events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", tradebot.db.base.UtcDateTime(timezone=True), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("portfolio_id", sa.Integer(), nullable=True),
        sa.Column("domain", sa.String(length=16), nullable=False),
        sa.Column("kind", sa.String(length=48), nullable=False),
        sa.Column("severity", sa.String(length=8), nullable=False),
        sa.Column("correlation_id", sa.String(length=36), nullable=True),
        sa.Column("message", sa.String(length=500), nullable=True),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_events_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_events")),
    )
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.create_index("ix_events_correlation", ["correlation_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_events_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_events_domain"), ["domain"], unique=False)
        batch_op.create_index(batch_op.f("ix_events_kind"), ["kind"], unique=False)
        batch_op.create_index(batch_op.f("ix_events_portfolio_id"), ["portfolio_id"], unique=False)
        batch_op.create_index("ix_events_user_created", ["user_id", "created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_events_user_id"), ["user_id"], unique=False)

    op.create_table(
        "sessions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", tradebot.db.base.UtcDateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", tradebot.db.base.UtcDateTime(timezone=True), nullable=True),
        sa.Column("user_agent", sa.String(length=255), nullable=True),
        sa.Column("ip_address", sa.String(length=64), nullable=True),
        sa.Column("created_at", tradebot.db.base.UtcDateTime(timezone=True), nullable=False),
        sa.Column("updated_at", tradebot.db.base.UtcDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_sessions_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sessions")),
    )
    with op.batch_alter_table("sessions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_sessions_token_hash"), ["token_hash"], unique=True)
        batch_op.create_index("ix_sessions_user_active", ["user_id", "revoked_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_sessions_user_id"), ["user_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("sessions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sessions_user_id"))
        batch_op.drop_index("ix_sessions_user_active")
        batch_op.drop_index(batch_op.f("ix_sessions_token_hash"))

    op.drop_table("sessions")
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_events_user_id"))
        batch_op.drop_index("ix_events_user_created")
        batch_op.drop_index(batch_op.f("ix_events_portfolio_id"))
        batch_op.drop_index(batch_op.f("ix_events_kind"))
        batch_op.drop_index(batch_op.f("ix_events_domain"))
        batch_op.drop_index(batch_op.f("ix_events_created_at"))
        batch_op.drop_index("ix_events_correlation")

    op.drop_table("events")
    with op.batch_alter_table("credentials", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_credentials_user_id"))
        batch_op.drop_index(batch_op.f("ix_credentials_provider_key"))

    op.drop_table("credentials")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_email"))

    op.drop_table("users")
    # ### end Alembic commands ###
