"""Add AI call log, lessons and per-portfolio model config

Revision ID: c9bfd0e85890
Revises: 4880702a7da0
Create Date: 2026-08-16 00:11:46.199674+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import tradebot.db.base


revision: str = "c9bfd0e85890"
down_revision: str | Sequence[str] | None = "4880702a7da0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "lessons",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("portfolio_id", sa.Integer(), nullable=False),
        sa.Column("position_id", sa.Integer(), nullable=True),
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column("closed_at", tradebot.db.base.UtcDateTime(timezone=True), nullable=False),
        sa.Column("holding_days", sa.Integer(), nullable=False),
        sa.Column("realized_return", sa.Numeric(precision=18, scale=8), nullable=False),
        sa.Column("benchmark_return", sa.Numeric(precision=18, scale=8), nullable=False),
        sa.Column("alpha", sa.Numeric(precision=18, scale=8), nullable=False),
        sa.Column("text", sa.String(length=1200), nullable=False),
        sa.ForeignKeyConstraint(
            ["portfolio_id"],
            ["portfolios.id"],
            name=op.f("fk_lessons_portfolio_id_portfolios"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_lessons")),
    )
    with op.batch_alter_table("lessons", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_lessons_closed_at"), ["closed_at"], unique=False)
        batch_op.create_index(
            "ix_lessons_portfolio_closed", ["portfolio_id", "closed_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_lessons_portfolio_id"), ["portfolio_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_lessons_symbol"), ["symbol"], unique=False)

    op.create_table(
        "ai_calls",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("decision_run_id", sa.Integer(), nullable=True),
        sa.Column("portfolio_id", sa.Integer(), nullable=False),
        sa.Column("correlation_id", sa.String(length=36), nullable=False),
        sa.Column("stage", sa.String(length=24), nullable=False),
        sa.Column("model", sa.String(length=120), nullable=False),
        sa.Column("endpoint", sa.String(length=200), nullable=False),
        sa.Column("rung", sa.String(length=16), nullable=False),
        sa.Column("prompt_tokens", sa.Integer(), nullable=False),
        sa.Column("completion_tokens", sa.Integer(), nullable=False),
        sa.Column("cached_tokens", sa.Integer(), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column("cost_usd", sa.Numeric(precision=18, scale=8), nullable=False),
        sa.Column("brief_hash", sa.String(length=32), nullable=False),
        sa.Column("system_prompt", sa.Text(), nullable=False),
        sa.Column("user_prompt", sa.Text(), nullable=False),
        sa.Column("response", sa.Text(), nullable=False),
        sa.Column("attempts", sa.JSON(), nullable=False),
        sa.Column("error", sa.String(length=500), nullable=True),
        sa.Column("created_at", tradebot.db.base.UtcDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["decision_run_id"],
            ["decision_runs.id"],
            name=op.f("fk_ai_calls_decision_run_id_decision_runs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["portfolio_id"],
            ["portfolios.id"],
            name=op.f("fk_ai_calls_portfolio_id_portfolios"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_calls")),
    )
    with op.batch_alter_table("ai_calls", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_ai_calls_correlation_id"), ["correlation_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_ai_calls_created_at"), ["created_at"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_ai_calls_decision_run_id"), ["decision_run_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_ai_calls_portfolio_id"), ["portfolio_id"], unique=False
        )
        batch_op.create_index("ix_ai_calls_run_stage", ["decision_run_id", "stage"], unique=False)

    with op.batch_alter_table("portfolios", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("ai_enabled", sa.Boolean(), nullable=False, server_default=sa.false())
        )
        batch_op.add_column(
            sa.Column("quality", sa.String(length=16), nullable=False, server_default="balanced")
        )
        batch_op.add_column(
            sa.Column(
                "deliberation",
                sa.String(length=32),
                nullable=False,
                server_default="firm_debate",
            )
        )
        batch_op.add_column(sa.Column("models", sa.JSON(), nullable=False, server_default="{}"))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("portfolios", schema=None) as batch_op:
        batch_op.drop_column("models")
        batch_op.drop_column("deliberation")
        batch_op.drop_column("quality")
        batch_op.drop_column("ai_enabled")

    with op.batch_alter_table("ai_calls", schema=None) as batch_op:
        batch_op.drop_index("ix_ai_calls_run_stage")
        batch_op.drop_index(batch_op.f("ix_ai_calls_portfolio_id"))
        batch_op.drop_index(batch_op.f("ix_ai_calls_decision_run_id"))
        batch_op.drop_index(batch_op.f("ix_ai_calls_created_at"))
        batch_op.drop_index(batch_op.f("ix_ai_calls_correlation_id"))

    op.drop_table("ai_calls")
    with op.batch_alter_table("lessons", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_lessons_symbol"))
        batch_op.drop_index(batch_op.f("ix_lessons_portfolio_id"))
        batch_op.drop_index("ix_lessons_portfolio_closed")
        batch_op.drop_index(batch_op.f("ix_lessons_closed_at"))

    op.drop_table("lessons")
    # ### end Alembic commands ###
