"""Allow re-entering a closed position

Revision ID: f308c69dc911
Revises: c9bfd0e85890
Create Date: 2026-08-16 02:52:35.033640+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = "f308c69dc911"
down_revision: str | Sequence[str] | None = "c9bfd0e85890"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("positions", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("uq_open_position"), type_="unique")
        batch_op.create_index(
            "uq_open_position",
            ["portfolio_id", "instrument_id"],
            unique=True,
            sqlite_where=sa.text("status = 'OPEN'"),
            postgresql_where=sa.text("status = 'OPEN'"),
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("positions", schema=None) as batch_op:
        batch_op.drop_index(
            "uq_open_position",
            sqlite_where=sa.text("status = 'OPEN'"),
            postgresql_where=sa.text("status = 'OPEN'"),
        )
        batch_op.create_unique_constraint(
            batch_op.f("uq_open_position"), ["portfolio_id", "instrument_id", "status"]
        )

    # ### end Alembic commands ###
