from decimal import Decimal

from sqlalchemy import func, select
from sqlalchemy.ext.asyncio import AsyncSession

from tradebot.core.clock import Clock, LiveClock
from tradebot.core.errors import ValidationError
from tradebot.core.money import quantize_cash
from tradebot.db.models import EntryType, LedgerEntry

ZERO = Decimal(0)


class Ledger:
    """Append-only cash record. Every balance in the system is a replay of this table.

    Nothing here updates or deletes a row: a correction is another entry, so the history stays
    auditable and a reconciliation can always recompute the truth.
    """

    def __init__(self, *, clock: Clock | None = None) -> None:
        self._clock = clock or LiveClock()

    async def balance(self, session: AsyncSession, portfolio_id: int) -> Decimal:
        total = await session.scalar(
            select(func.coalesce(func.sum(LedgerEntry.amount), 0)).where(
                LedgerEntry.portfolio_id == portfolio_id
            )
        )
        return quantize_cash(Decimal(total or 0))

    async def post(
        self,
        session: AsyncSession,
        *,
        portfolio_id: int,
        entry_type: str,
        amount: Decimal,
        ref_type: str | None = None,
        ref_id: int | None = None,
        memo: str | None = None,
        allow_negative: bool = False,
    ) -> LedgerEntry:
        amount = quantize_cash(amount)
        running = await self.balance(session, portfolio_id) + amount

        if running < ZERO and not allow_negative:
            raise ValidationError(f"entry would overdraw cash: balance would be {running}")

        entry = LedgerEntry(
            portfolio_id=portfolio_id,
            at=self._clock.now(),
            entry_type=entry_type,
            amount=amount,
            balance_after=quantize_cash(running),
            ref_type=ref_type,
            ref_id=ref_id,
            memo=memo,
        )
        session.add(entry)
        await session.flush()
        return entry

    async def deposit(
        self, session: AsyncSession, *, portfolio_id: int, amount: Decimal, memo: str | None = None
    ) -> LedgerEntry:
        if amount <= ZERO:
            raise ValidationError("a deposit must be positive")
        return await self.post(
            session,
            portfolio_id=portfolio_id,
            entry_type=EntryType.DEPOSIT,
            amount=amount,
            memo=memo,
        )

    async def replay(self, session: AsyncSession, portfolio_id: int) -> Decimal:
        """Recompute the balance from zero, ignoring every stored `balance_after`."""
        rows = await session.scalars(
            select(LedgerEntry)
            .where(LedgerEntry.portfolio_id == portfolio_id)
            .order_by(LedgerEntry.id)
        )
        running = ZERO
        for entry in rows:
            running += entry.amount
        return quantize_cash(running)

    async def find_drift(self, session: AsyncSession, portfolio_id: int) -> list[int]:
        """Entry ids whose recorded running balance disagrees with a replay to that point."""
        rows = await session.scalars(
            select(LedgerEntry)
            .where(LedgerEntry.portfolio_id == portfolio_id)
            .order_by(LedgerEntry.id)
        )
        running = ZERO
        drifted: list[int] = []
        for entry in rows:
            running += entry.amount
            if quantize_cash(running) != quantize_cash(entry.balance_after):
                drifted.append(entry.id)
        return drifted

    async def realized_total(self, session: AsyncSession, portfolio_id: int) -> Decimal:
        """Cash actually generated by trading: sales less purchases less fees."""
        total = await session.scalar(
            select(func.coalesce(func.sum(LedgerEntry.amount), 0)).where(
                LedgerEntry.portfolio_id == portfolio_id,
                LedgerEntry.entry_type.in_((EntryType.BUY, EntryType.SELL, EntryType.FEE)),
            )
        )
        return quantize_cash(Decimal(total or 0))
